# version: '3.8'

services:
  gpu-jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - "C:/Users/lobra/Documents/Notebooks/UCB:/home/lobral/notebooks"
    container_name: gpu_jupyter_env
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: jupyter notebook --notebook-dir=/home/lobral/notebooks --ip=0.0.0.0 --port=8888 --no-browser --allow-root